version: "3"
services:
  # Redis service
  redis1:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  redis2:
    image: redis:latest
    container_name: my-redis1
    ports:
      - "6380:6379"
    networks:
      - my-network

  redis3:
    image: redis:latest
    container_name: my-redis2
    ports:
      - "6381:6379"
    networks:
      - my-network

  # Service Discovery service
  service_discovery:
    build:
      context: ./service_discovery
    container_name: my-service-discovery
    ports:
      - "8082:8082"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  accounts_service:
    build:
      context: ./accounts_management
    container_name: my-accounts-service
    ports:
      - "5000:5000"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  accounts_service1:
    build:
      context: ./accounts_management
    container_name: my-accounts-service1
    ports:
      - "5001:5000"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  accounts_service2:
    build:
      context: ./accounts_management
    container_name: my-accounts-service2
    ports:
      - "5002:5000"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  template_service:
    build:
      context: ./templates_management
    container_name: my-template-service
    ports:
      - "5005:5005"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  template_service1:
    build:
      context: ./templates_management
    container_name: my-template-service1
    ports:
      - "5006:5005"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  template_service2:
    build:
      context: ./templates_management
    container_name: my-template-service2
    ports:
      - "5007:5005"
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

  # Gateway service
  gateway:
    build:
      context: ./gateway
    container_name: my-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service_discovery
      - accounts_service
      - accounts_service1
      - accounts_service2
      - template_service
      - template_service1
      - template_service2
      - redis1
      - redis2
      - redis3
    links:
      - redis1
      - redis2
      - redis3
    networks:
      - my-network

networks:
  my-network:
