# Use the official Golang image as the base image
FROM golang:1.20

# Set the working directory in the container
WORKDIR /app

# Copy the Go modules and Go source code into the container
COPY go.mod go.sum ./
COPY main.go .

# Download Go dependencies
RUN go mod download

# Build the Go application
RUN go build -o gateway-service

# Expose the port the application will run on
EXPOSE 8080

# Command to run the executable
CMD ["./gateway-service"]

